[env:jc4827w543]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB
board_build.partitions = default.csv

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
	-DBOARD_HAS_PSRAM
	-DLV_CONF_INCLUDE_SIMPLE
	-I include
	-DARDUINO_USB_CDC_ON_BOOT=1

extra_scripts = post:copy_firmware.py

build_src_filter =
	+<*>
	+<${platformio.libdeps_dir}/${PIOENV}/lvgl/demos>

lib_deps =
	moononournation/GFX Library for Arduino @ ^1.4.9
	tamctec/TAMC_GT911 @ ^1.0.2
	lvgl/lvgl @ ^8.3.11
	bblanchon/ArduinoJson @ ^7.0.0
